# Generated by Django 3.0.4 on 2020-04-03 22:36

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Product')),
                ('color', models.CharField(max_length=255, verbose_name='Color of Product')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventory', models.PositiveIntegerField(verbose_name='Quantity of Products in Stock')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description of Product')),
                ('weigth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weigth of product')),
                ('status', models.BooleanField(default=True, verbose_name='Status of Product')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Product Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
