# Generated by Django 3.0.4 on 2020-05-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200507_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='promo_price',
            new_name='sale_price',
        ),
    ]
