# Generated by Django 3.0.4 on 2020-05-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200507_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='inventory',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
