# Generated by Django 3.0.4 on 2020-04-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200409_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='settings.STATIC_ROOT/images/placeholder.png', upload_to='settings.MEDIA_ROOT/images/'),
        ),
    ]
