# Generated by Django 3.0.4 on 2020-04-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200410_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
