# Generated by Django 3.0.4 on 2020-05-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200522_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='modified',
        ),
    ]
