# Generated by Django 3.0.4 on 2020-04-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200415_0103'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addresses',
        ),
        migrations.AddField(
            model_name='user',
            name='addressess',
            field=models.ManyToManyField(related_name='user_adressess', through='addresses.AddressInfo', to='addresses.Address'),
        ),
    ]
