# Generated by Django 3.0.4 on 2020-05-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200521_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
