# Generated by Django 3.0.4 on 2020-04-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200415_0103'),
        ('users', '0003_auto_20200415_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(related_name='user_adresses', through='addresses.AddressInfo', to='addresses.Address'),
        ),
    ]
