# Generated by Django 3.0.4 on 2020-04-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200403_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
