# Generated by Django 3.0.4 on 2020-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200411_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.CharField(blank=True, max_length=8, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.CharField(default='', max_length=9, verbose_name='RG'),
        ),
    ]
