# Generated by Django 3.0.4 on 2020-09-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
