# Generated by Django 3.0.4 on 2020-09-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200920_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem do Produto'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
