# Generated by Django 3.0.4 on 2020-10-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201012_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço Promocional(R$)'),
        ),
    ]
