# Generated by Django 3.0.4 on 2020-10-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201012_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='sale_price',
        ),
    ]
