# Generated by Django 3.0.4 on 2020-10-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201012_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='discount_price',
        ),
    ]
