# Generated by Django 3.0.4 on 2020-10-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201012_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/categories/', verbose_name='Imagem da Categoria'),
        ),
    ]
