# Generated by Django 3.0.4 on 2020-12-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20201207_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo para Produção'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço de Custo'),
        ),
    ]
