# Generated by Django 3.0.4 on 2020-05-21 23:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('receiver_name', models.CharField(blank=True, help_text='Nome do destinatário', max_length=255, null=True, verbose_name='Destinatário')),
                ('receiver_phone', models.CharField(blank=True, help_text='DDD + n.º. Exemplo: (11) 96123-4567', max_length=20, null=True, verbose_name='Telefone')),
                ('nickname', models.CharField(blank=True, help_text='Identificador. Exemplo: Casa da Praia', max_length=255, verbose_name='Identificador')),
                ('address_type', models.CharField(choices=[('EE', 'Endereço de Entrega'), ('ES', 'Endereço Secundário')], default='EE', max_length=2, verbose_name='Tipo')),
                ('postal_code', models.CharField(help_text='8 Dígitos. Exemplo: 12345-678', max_length=8, verbose_name='CEP')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='AC', max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('extra_data', models.CharField(blank=True, help_text='Complemento. Exemplo: Ao lado do mercado', max_length=255, null=True, verbose_name='Obs.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
