# Generated by Django 3.0.4 on 2020-05-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20200429_1253'),
        ('addresses', '0003_auto_20200520_1756'),
    ]

    operations = [
    ]
