# Generated by Django 3.0.4 on 2020-05-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20200429_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressInfo',
        ),
    ]
