# Generated by Django 3.0.4 on 2020-06-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200522_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço Promocional(R$)'),
        ),
    ]
