# Generated by Django 3.0.4 on 2020-09-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200916_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço Promocional(R$)'),
        ),
    ]
