# Generated by Django 3.0.4 on 2020-10-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20201012_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='order',
            name='obs',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=1000),
        ),
    ]
