# Generated by Django 3.0.4 on 2020-10-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20201012_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(default='Deposito', max_length=1000),
        ),
    ]
