# Generated by Django 3.0.4 on 2020-10-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_payment_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
