# Generated by Django 3.0.4 on 2020-10-13 00:43

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='pk', unique=True, verbose_name='Registro digital'),
        ),
    ]
