# Generated by Django 3.0.4 on 2020-12-07 08:47

import costura.users.validators
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_order_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserlessOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='pk', unique=True, verbose_name='Registro digital')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Aguardando Pagamento'), (1, 'Compra Concluída'), (2, 'Compra CANCELADA')], default=0, verbose_name='Situação')),
                ('items', models.CharField(max_length=1000)),
                ('payment_option', models.CharField(default='Deposito', max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('total', models.CharField(max_length=200)),
                ('ship', models.CharField(max_length=200)),
                ('final', models.CharField(max_length=200)),
                ('obs', models.CharField(default='', max_length=200)),
                ('cpf', models.CharField(max_length=14, validators=[costura.users.validators.validate_cpf], verbose_name='CPF')),
                ('phone', models.CharField(max_length=13, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Pedido sem Usuário',
                'verbose_name_plural': 'Pedidos sem Usuário',
            },
        ),
    ]
