# Generated by Django 3.0.4 on 2020-09-13 01:05

import costura.users.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200912_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='', max_length=14, validators=[django.core.validators.RegexValidator(re.compile('^\\d{3}\\.?\\d{3}\\.?\\d{3}\\-?\\d{2}$'), 'Informe um CPF válido. Este valor deve conter apenas números (0-9),ponto (.) e hifen (-)', 'invalid'), costura.users.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
