# Generated by Django 3.0.4 on 2020-09-13 01:18

import costura.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200912_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='', max_length=14, validators=[costura.users.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
