# Generated by Django 3.0.4 on 2020-09-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200913_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cliente'),
        ),
    ]
