# Generated by Django 3.0.4 on 2020-09-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200913_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_number',
            field=models.PositiveIntegerField(blank=True, verbose_name='Número de Registro'),
        ),
    ]
