# Generated by Django 3.0.4 on 2020-09-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200913_0203'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staff',
            managers=[
            ],
        ),
    ]
