# Generated by Django 3.0.4 on 2020-09-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200913_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_nickname',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_number',
        ),
    ]
