# Generated by Django 3.0.4 on 2020-09-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200913_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
