# Generated by Django 3.0.4 on 2020-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.CharField(blank=True, max_length=8, verbose_name='Prefixo'),
        ),
    ]
